# Copyright 2022 The OpenSDS Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Check for gelato source code existed
  stat:
    path: "{{ gelato_work_dir }}"
  ignore_errors: yes
  register: gelatoexisted

- name: Download gelato ansible installer source code
  git:
    repo: "{{ gelato_remote_url }}"
    dest: "{{ gelato_work_dir }}"
    version: "{{ gelato_repo_branch }}"
  when:
    - gelatoexisted.stat.exists is undefined or gelatoexisted.stat.exists == false

- name: Copy gelato configs group_vars files into gelato installer group_vars directory
  copy:
    src: "../../../group_vars/{{ item }}"
    dest: "{{ gelato_work_dir }}/installer/ansible/group_vars/{{ item }}"
  with_items:
    - common.yml
    - gelato.yml
    - gelato-ha.yml  

- name: Ping all hosts and run gelato ansible playbook
  shell: "{{ item }}"
  with_items:
    - ansible all -m ping -i local.hosts
    - ansible-playbook site.yml -i local.hosts | tee /var/log/gelato_ansible.log
  args:
    chdir: "{{ gelato_work_dir }}/installer/ansible"
  register: ansible_stdout
  