# This is the GitHub Action to run the CI for SODA Installer for all pull requests

name: SODA Installer CI

# Controls when the action will run. 
# Triggers the workflow on push or pull request events but only for the main branch
# Allows you to run this workflow manually from the Actions tab
on: [pull_request, workflow_dispatch]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go-version: [1.17.9]
        os: [ubuntu-20.04]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: ${{ matrix.go-version }}
          # Whether to download only stable versions
          stable: true # optional, default is true
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout the repository
        uses: actions/checkout@v2
      
      - name: Install Pre-requisites
        run: |
          wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
          echo deb https://download.ceph.com/debian-luminous/ xenial main | sudo tee /etc/apt/sources.list.d/ceph.list
          sudo apt-get update && sudo apt-get install -y libcephfs-dev librbd-dev librados-dev
      
      - name: 'Make the CI check executable and initiate the testing with SODA delfin'
        run: |
          sudo chmod +x ./ci/ci_check.sh
          ./ci/ci_check.sh delfin
        shell: bash
        if: ${{ always() }}

      - name: 'Make the CI check executable and initiate the testing with SODA hotpot'
        run: |
          sudo chmod +x ./ci/ci_check.sh
          ./ci/ci_check.sh hotpot
        shell: bash
        env:
          GOPATH: "/home/runner/work/installer/"
        if: ${{ always() }}

